# Generated by Django 5.1.4 on 2025-02-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timehero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='task',
            name='failed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
