# Generated by Django 5.1.4 on 2025-02-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timehero', '0002_task_completed_count_task_duration_task_failed_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='position_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='position_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
