# Generated by Django 5.1.4 on 2025-03-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timehero', '0002_user_is_locked_user_last_attempt_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='unlock_condition',
            field=models.IntegerField(default=0),
        ),
    ]
