# Generated by Django 5.1.4 on 2025-02-04 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timehero', '0003_task_position_x_task_position_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='duration',
        ),
    ]
