# Generated by Django 5.1.4 on 2025-03-13 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timehero', '0004_badge_competition_competitionranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 21, 12, 40, 529866, tzinfo=datetime.timezone.utc)),
        ),
    ]
