# Generated by Django 5.1.4 on 2025-03-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timehero', '0007_task_checklist_task_notes_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checklist_completed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
