# Generated by Django 5.1.4 on 2025-03-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timehero', '0008_task_checklist_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='unlock_condition',
        ),
        migrations.AddField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(choices=[('tasks_completed', '完成任务数'), ('priority_tasks', '高优先级任务数'), ('hard_tasks', '高难度任务数'), ('daily_tasks', '每日完成任务数'), ('notes_written', '笔记数量'), ('tags_used', '标签种类')], default='tasks_completed', max_length=32),
        ),
        migrations.AddField(
            model_name='achievement',
            name='target_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='hard_tasks_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='high_priority_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tasks_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
