# Generated by Django 5.1.4 on 2025-03-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timehero', '0009_remove_achievement_unlock_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tasks_completed',
        ),
    ]
