# Generated by Django 5.1.4 on 2025-03-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timehero', '0011_user_tasks_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='condition_type',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='target_value',
        ),
        migrations.RemoveField(
            model_name='task',
            name='checklist_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hard_tasks_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='high_priority_tasks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tasks_completed',
        ),
        migrations.AddField(
            model_name='achievement',
            name='unlock_condition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='unlocked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
